gitops-runtime:
  global:
    codefresh:
      accountId: 6560603b9efd8cf388d6fb70
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
